name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Install pkg
        run: npm i pkg

      - name: Build
        run: npx pkg index.js

      - name: Print
        run: ls -la

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 7
          format: "YYYY-MM-DD_HH.mm"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: iStock_${{ steps.time.outputs.time }}
          release_name: "[${{ steps.time.outputs.time }}] iStock"
          draft: false
          prerelease: false

      - name: Upload Release Asset Linux
        id: upload_release_asset_linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: index-linux
          asset_name: istock-linux

      - name: Upload Release Asset Mac
        id: upload_release_asset_mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: index-macos
          asset_name: istock-macos

      - name: Upload Release Asset Win
        id: upload_release_asset_win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: index-win.exe
          asset_name: istock-win.exe
