name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nexe
        run: sudo npm i -g nexe

      - name: Build
        run: nexe --build index.js
