name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Install pkg
        run: npm i pkg

      - name: Build
        run: npx pkg index.js

      - name: Print
        run: ls -la
