name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Install nexe
        run: npm i nexe

      - name: Build
        run: node node_modules/nexe --build index.js
